modLoader="javafml" #mandatory
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/GT-Rubber" #optional

[[mods]]
modId="gtrubber" #mandatory
version="${version}"
displayName="GT Rubber" #mandatory
credits="Thanks for this example mod goes to Java"
authors="Trinsdar"
description='''Just a simple mod that adds gregtech's rubber trees.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gtrubber]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtrubber]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtrubber]]
    modId="antimatter"
    mandatory=true
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"
